### ISSUE TITLE
Clicking the back button on any of the views(timeline,topics,events) returns a black screen.

### ISSUE THREAD

**Issue by RoyPuja** [WomenWhoCode/WomenWhoCode#371]
On clicking the phone back button from any of the tabs returns a black screen and on another back button click the app closes. The app should close on the first back button click from those views.

**Comment by zassmin** [comment]
@RoyPuja Thanks for finding the bug and for bringing it up. I started reading the up/back navigation guidelines, http://developer.android.com/intl/es/design/patterns/navigation.html to get a better understanding of what should truly be happening for the user. It appears that up/back should have the same navigation within the app except for these differences: 
* with back button you can also: 
  * close a dialogue modal 
  * navigate outside of that app

I also tested with a few google apps like gmail and hangouts to find out what their behavior was and it matches the above. 

For whoever working on this bug, please make sure the back button, navigates to the last screen you were on.

**Comment by chhavip** [comment]
@zassmin , would like to get started on this, if you could point out any problem areas to keep specifically in mind?

**Comment by zassmin** [comment]
@chhavip awesome! It looks like when you click back on the timeline, topics and events you back a black screen. I haven't tested this myself. I recommended walking through the app to figure out if where exactly the problems are. @RoyPuja would also have more insight here. 

Please follow the developer guidelines http://developer.android.com/intl/es/design/patterns/navigation.html, in general, the back button should take the user to the previous screen they were on, regardless of whether that is from inside or outside of the app. 

I would only cover anything after 'create profile' and on for the purposes of this issue. Or in other words, start with the timeline view since that is what initially launches after a user has successfully logged in or created an account.

**Comment by chhavip** [comment]
@zassmin , having a problem in signing in, network parse error, is the user stored locally or is there a server where signed up information is stored?

**Comment by zassmin** [comment]
@chhavip the user is stored in [Parse](http://parse.com/). Try creating a new account, it could be that your creds are wrong.

**Comment by chhavip** [comment]
@zassmin, was able to login, there is one concern though as parse has announced shut down of services within a year, I believe a migration to some other backend service provider will be required.

**Comment by zassmin** [comment]
@chhavip great question! Parse will still be available throughout the year, which means we have some time. In the meantime, we are building our own backend/api. 

Worst case, we export our data to a mongo db server and use the open source lib that parse will have, which does the queries/api calls.

**Comment by chhavip** [comment]
@zassmin , yes, slack for people contributing to this app, it ll be easier to clear doubts and discuss best policies, a link could be left in the readme for anyone wishing to join

**Comment by zassmin** [comment]
closed by https://github.com/WomenWhoCode/WomenWhoCode/pull/410
